### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by craciunchan** [jbouzekri/free-bet#7]
Hello

Can you add a balance?
deposit and withdrawal points
Also how do I login to admin panel?

**Comment by jbouzekri** [comment]
Hi @craciunchan,

Can you detail what you mean by balance/deposit/withdrawal ? I don't see what you mean.

There is no admin panel right now. For now, the only other thing an admin can do from a classic user is to set the results of a game. But I am open to any new feature you think might be useful. So do not hesitate to describe what you want or to create a pull request.

Regards

**Comment by craciunchan** [comment]
I will be very fast
Can you create a db with?
User
Bets
History
Points
Deposit and withdrawal balance point
If you make this I will give you 50% of all my profit
I just want a simply script
-people deposit and withdrawal points via pp others
-admin can create simple bet like "who will win?"
-admin confirm and canceled bet.

**Comment by jbouzekri** [comment]
The last point seems straightforward. A simple CRUD UI would do the job.

The first 2 are more difficult as it is not the way it works right now. Currently, people says who will win and earn a fix number of point. You do not "gamble" point on the bet. So it would require some work to do it. However, I think all items are abstracted enough so that you could do it without redoing everything.

You already have the User, Bet, History entity. Moreover people earn points by betting. But yes this is not a balance. More like a cumulative score.

Sadly I won't have time right now to work on that. I am always open to integrate pull requests so do not hesitate if you take the time to implement it. I will add this to my personal backlog but It won't be before september most probably.

**Comment by craciunchan** [comment]
How do I add bets?
Can you add to your demo?
Thank you for all reply.

**Comment by jbouzekri** [comment]
You did not see any bet in the demonstration because there were no event in the future. I have changed my fixtures to increase the archived events of one year. You should see some events where you can bet on it right now.

If you want in your own installation, this is what I changed. In the file `src/FreeBet/Bundle/SoccerWorldCupBundle/DataFixtures/MongoDB/LoadMatchData.php`, in the method `createMatch`, I have replaced : 

``` php
$entity->setDate(\DateTime::createFromFormat('Y-m-d H:i:s', $data[5]));
```

with : 

``` php
$date = \DateTime::createFromFormat('Y-m-d H:i:s', $data[5]);
$date->modify('+1 year');
$entity->setDate($date);
```

**Comment by craciunchan** [comment]
Tell me,when can make a db?
This script is so wonderful
I will try to make something with.
